<?php

declare(strict_types=1);

namespace AndyDefer\Actions\Enums;

/**
 * Defines all available HTTP response types that can be generated by ResponseFactory.
 *
 * This enum maps each response type to its string representation, which is used
 * internally by ResponseFactory to determine which conversion method to call
 * when toResponse() is invoked.
 *
 * Each case corresponds to a specific HTTP response type:
 * - JSON: API JSON responses
 * - REDIRECT: HTTP redirects to URLs
 * - REDIRECT_ROUTE: HTTP redirects to named routes
 * - REDIRECT_BACK: HTTP redirects to the previous page
 * - STREAM: Streamed responses for large data transfer
 * - SSE: Server-Sent Events for real-time notifications
 * - NO_CONTENT: 204 No Content responses
 * - INERTIA: Inertia.js responses for SPA applications
 * - HTML: Raw HTML responses
 * - FILE_INLINE: Files displayed inline in the browser
 * - FILE_DOWNLOAD: Files forced to download
 * - TEXT: Plain text responses
 * - VIEW: Blade view responses
 *
 * @example
 * $type = HttpResponseType::JSON;
 * echo $type->value; // 'json'
 *
 * @author Andy Defer
 */
enum HttpResponseType: string
{
    /**
     * JSON response for API endpoints.
     *
     * Converts AbstractData objects to camelCase arrays automatically.
     */
    case JSON = 'json';

    /**
     * Redirect response to an absolute URL.
     */
    case REDIRECT = 'redirect';

    /**
     * Redirect response to a named route.
     */
    case REDIRECT_ROUTE = 'redirectRoute';

    /**
     * Redirect response back to the previous page.
     */
    case REDIRECT_BACK = 'redirectBack';

    /**
     * Streamed response for large data or real-time output.
     */
    case STREAM = 'stream';

    /**
     * Server-Sent Events response for real-time push notifications.
     */
    case SSE = 'sse';

    /**
     * 204 No Content response for successful requests without response body.
     */
    case NO_CONTENT = 'noContent';

    /**
     * Inertia.js response for modern single-page applications.
     */
    case INERTIA = 'inertia';

    /**
     * Raw HTML response for emails, legacy views, or external integrations.
     */
    case HTML = 'html';

    /**
     * File response with inline disposition (browser displays the file).
     */
    case FILE_INLINE = 'fileInline';

    /**
     * File response with attachment disposition (browser downloads the file).
     */
    case FILE_DOWNLOAD = 'fileDownload';

    /**
     * Plain text response for logs, configuration files, or simple endpoints.
     */
    case TEXT = 'text';

    /**
     * Blade view response for legacy Laravel views.
     */
    case VIEW = 'view';
}
